name: New PR Automation
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  pr_opened_and_reopened:
    name: pr_opened_and_reopened
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - name: "Ntification"
        run: echo "placeholder"
